### ISSUE TITLE
Segmentation fault with vim-fugitive/github-issues.vim

### ISSUE THREAD

**Issue by ntnn** [neovim/python-client#80]
When using [vim-fugitive](/tpope/vim-fugitive) with `:Gcommit` or [github-issues.vim](/jaxbot/github-issues.vim) with `:Gissues` it produces the output pasted below, leading into a segfault.

The problem also appears with github-issues.vim disabled, and the plugins work fine in Vim 7.4.

Neovim version compiled today (see paste below), python-client 0.0.26:
```
>pip freeze | grep neovim
neovim==0.0.26
```

Neovim error output, every second 'Press Enter[...]' line removed:
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "<string>", line 317, in run
  File "<string>", line 112, in getUpstreamRepoURI
  File "<string>", line 32, in getRepoURI
  File "/home/ntnn/.local/lib/python2.7/site-packages/neovim/api/nvim.py", line 239, in buffer
    return self._session.request('vim_get_current_buffer')
  File "/home/ntnn/.local/lib/python2.7/site-packages/neovim/api/common.py", line 220, in request
    return walk(self._in, self._session.request(name, *args), self, name,
  File "/home/ntnn/.local/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 72, in request
    err, rv = self._yielding_request(method, args)
  File "/home/ntnn/.local/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 133, in _yielding_request
    return parent.switch()
AttributeError: 'NoneType' object has no attribute 'switch'
Press ENTER or type command to continue
Press ENTER or type command to continue[1]    17965 segmentation fault (core dumped)  NVIM_PYTHON_LOG_LEVEL='INFO' NVIM_PYTHON_LOG_FILE='neovim.log' nvim
```
Neovim logfile set to info:
```
2015-02-03 13:38:54,030 [WARNING @ async_session.py:_on_message:69] 15024 - Traceback (most recent call last):
  File "/home/ntnn/.local/lib/python2.7/site-packages/neovim/msgpack_rpc/async_session.py", line 66, in _on_message
    self._handlers.get(msg[0], self._on_invalid_message)(msg)
  File "/home/ntnn/.local/lib/python2.7/site-packages/neovim/msgpack_rpc/async_session.py", line 87, in _on_response
    self._pending_requests.pop(msg[1])(msg[2], msg[3])
  File "/home/ntnn/.local/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 129, in response_cb
    gr.switch(err, rv)
error: cannot switch to a different thread
```
Neovim version:
```
>nvim --version
NVIM 0.0.0-alpha+201502021723 (compiled Feb  3 2015 12:51:44)
Commit: 7751cd21f5ae8952f578a0ccd892e32c95a4ae8a
Build type: Debug
Compilation: /bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/ntnn/prog/neovim/build/config -I/home/ntnn/prog/neovim/src -I/home/ntnn/prog/neovim/.deps/usr/include -I/home/ntnn/prog/neovim/.deps/usr/include -I/home/ntnn/prog/neovim/.deps/usr/include/luajit-2.0 -I/usr/include -I/home/ntnn/prog/neovim/build/src/nvim/auto -I/home/ntnn/prog/neovim/build/include
Compiled by root@Persephone  Features included (+) or not (-):
+acl             +extra_search    +mouse_dec       +tag_binary
+arabic          +farsi           -mouse_gpm       +tag_old_static
+autocmd         +file_in_path    +mouse_netterm   -tag_any_white
-browse          +find_in_path    +mouse_sgr       +terminfo
+byte_offset     +folding         -mouse_sysmouse  +termresponse
+cindent         -footer          +mouse_urxvt     +textobjects
-clipboard       +fork()          +mouse_xterm     +title
+cmdline_compl   +gettext         +multi_byte      -toolbar
+cmdline_hist    +iconv           +multi_lang      +user_commands
+cmdline_info    +insert_expand   +path_extra      +vertsplit
+comments        +jumplist        +persistent_undo +virtualedit
+conceal         +keymap          +postscript      +visual
+cscope          +langmap         +printer         +visualextra
+cursorbind      +libcall         +profile         +viminfo
+cursorshape     +linebreak       +quickfix        +vreplace
+dialog_con      +lispindent      +reltime         +wildignore
+diff            +listcmds        +rightleft       +wildmenu
+digraphs        +localmap        +scrollbind      +windows
-dnd             +menu            +signs           +writebackup
-ebcdic          +mksession       +smartindent     -X11
-emacs_tags      +modify_fname    +startuptime     -xfontset
+eval            +mouse           +statusline      -xsmp
+ex_extra        -mouseshape      +syntax          -xterm_clipboard
   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "$HOME/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/nvim"

```

Maybe this helps too:

Output of attached python-repl:
```
>>> nvim.command(':Gcommit')
INFO:neovim.msgpack_rpc.session:'Received error: [0, 'Vim(return):Invalid channel "1"']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ntnn/.local/lib/python2.7/site-packages/neovim/api/nvim.py", line 121, in command
    return self._session.request('vim_command', string)
  File "/home/ntnn/.local/lib/python2.7/site-packages/neovim/api/common.py", line 220, in request
    return walk(self._in, self._session.request(name, *args), self, name,
  File "/home/ntnn/.local/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 77, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: Vim(return):Invalid channel "1"
```

**Comment by starcraftman** [comment]
@tarruda Any update on this bug? I just ran into something similar, see my issue 23. junegunn requested I investigate python on neovim as a fallback for jobs api (since I already did the update). Seems to be related to the fact my spawned threads are attempting to access vim.current.buffer.

It doesn't bother me too much, but other plugins may do something similar. We can just disable the python option for nvim.

**Comment by tarruda** [comment]
> Seems to be related to the fact my spawned threads are attempting to access vim.current.buffer.

Is this supported by vim? As far as I know vim/python API is not thread-safe. cc @ZyX-I

In any case you should be able to access the vim module from other threads using something like this: `vim.session.threadsafe_call(lambda: vim.current.buffer[0] = 'line')`

**Comment by starcraftman** [comment]
@tarruda I don't know if it was intentionally supported by vim, perhaps more accidentally works as a consequence to their implementation. It is definitely not thread safe, I use a shared python lock to sequence writes to vim.current.buffer. With normal vim, I imagine it works because all the threads spawned share access to the same vim.current.buffer from the __main__ thread. Whereas with nvim, it is only available in other threads via your rpc mechanism.

I will try the code provided and look at your session class. Thanks for the speedy response & awesome work.

**Comment by tarruda** [comment]
>  It is definitely not thread safe, I use a shared python lock to sequence writes to vim.current.buffer.

It doesn't matter if you use a lock since vim main thread doesn't know it exists. It could be an accident that you can read from `vim.current.buffer` from other threads(your'e assuming that evaluating this expression won't cause any writes in the C layer)

One of your threads could writing to `vim.current.buffer` at the same time vim main thread is accessing it(through the native C API) and it wont know about your lock. There's a good chance running vim with your plugin under helgrind or TSAN will report data races.

**Comment by starcraftman** [comment]
@tarruda I don't think I made it clear, but both the python & ruby versions of the parallel installer are synchronous functions (as opposed to your jobs api). So the main loop blocks until finished/aborted via interrupt, preventing any such issues. So that's why the python lock is sufficient.

**Comment by tarruda** [comment]
> @tarruda I don't think I made it clear, but both the python & ruby versions of the parallel installer are synchronous functions (as opposed to your jobs api). So the main loop blocks until the threads finish or get aborted via interrupt, preventing any such issues. So that's why the python lock is sufficient to just sequence the threads I make.

:+1: makes sense, thanks for explaining. Still, its not possible to access the API for the python client from multiple threads unless you use `threadsafe_call` explicitly, though I might fix that in the future.

**Comment by starcraftman** [comment]
@tarruda Sounds fine. I can understand this particular corner case might not be top priority. Plugins can just avoid it.

To summarize if other run across this bug. Python plugins can:
1) Have threads use `vim.session.threadsafe_call()`
2) Simply delegate all vim interaction to __main__ .

**Comment by Shougo** [comment]
> Is this supported by vim? As far as I know vim/python API is not thread-safe. cc @ZyX-I

Yes.  It is not thread safe.  It is too dangerous.
So, I don't want to create multi thread plugins for the external interfaces.

**Comment by tarruda** [comment]
@Shougo I think in the case of vim-plug its relatively safe since vim is blocked while threads are running, but if a signal is received then it could result in a crash

**Comment by brookhong** [comment]
vim.session.threadsafe_call can not be used to call vim.eval, since vim.eval has something returned.

Is it possible to support that?

**Comment by starcraftman** [comment]
@brookhong The above conversation was specifically about multiple python threads using commands to modify vimscript variables & buffers. `vim.eval` should be fine in a threaded context as you are only asking the vimscript engine to fetch variables or evaluate a function with args.

**Comment by brookhong** [comment]
@starcraftman I read this thread completely, actually I'm trying to make a plugin https://github.com/brookhong/DBGPavim/issues/37 support Neovim.

DBGPavim uses python threading, and vim.eval is also called in a threaded context, which is raising a same error as in this thread.

**Comment by starcraftman** [comment]
@brookhong Ah alright, sorry then, was just wanting to be sure it was clear. I made vim-plug work mainly by pushing back into __main__ most vim.command/eval code. You'll probably have to wait until this is solved or change the way the threads work.

**Comment by brookhong** [comment]
Did you use vim.eval in threaded context?

In your commit to vim-plug, the calls to vim.eval seem not be in a thread.

**Comment by starcraftman** [comment]
@brookhong Not currently, previously I had some that I moved into globals. I just tried this and you can see it works. Won't log actually unless g:plug_log_on = 1. 

```diff
diff --git a/plug.vim b/plug.vim
index d71f070..faa3f20 100644
--- a/plug.vim
+++ b/plug.vim
@@ -1314,6 +1314,7 @@ class PlugThread(thr.Thread):
     buf_q, work_q, lock = self.args
 
     try:
+      GLog.write('Update: ' + str(vim.eval('s:update')))
       while not G_STOP.is_set():
         name, args = work_q.get_nowait()
         GLog.write('{0}: Dir {1}'.format(name, args['dir']))

```

**Comment by bfredl** [comment]
it is documented now the api is not threadsafe, except for `nvim.async_call`.
